### PR TITLE
fix(UserRegistration): Allow spaces and - in first and last name

### LINKED ISSUE #183: Allow first name and last name to contain space and dash
Allow users to enter spaces and dashes in their first and last names when registering for a new account. The spaces and dashes will be removed when their username is generated but will be kept in their first name and last name for when their name is displayed.

### PR DESCRIPTION
**Pull request by ccwemett**
## Changes

- Validator allows characters A-Z, a-z, spaces, and dashes within user's first and last name
- Student username generation removes spaces and dashes from the first name
- Teacher username generation removes spaces and dashes from first and last name

## Test
- Validator correctly checks the first and last name
- Username generation appropriately removes any dashes or spaces within the first and last name

Closes #183

### CODE REVIEW

File: src/main/java/org/wise/portal/domain/authentication/impl/TeacherUserDetails.java [hunk 1]
```diff
@@ -165,7 +165,7 @@ public class TeacherUserDetails extends PersistentUserDetails implements Mutable
   private String howDidYouHearAboutUs;
 
   public String getCoreUsername() {
-    return firstname + lastname;
+    return firstname.replaceAll("[\\s-]+", "") + lastname.replaceAll("[\\s-]+", "");
```
Comment (geoffreykwan) [inline src/main/java/org/wise/portal/domain/authentication/impl/TeacherUserDetails.java]: I think we can change this to just call replaceAll once.

```return (firstname + lastname).replaceAll("[\\s-]+", "");```

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Functionality works well. I have a minor code refactor suggestion.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Review by geoffreykwan — APPROVED** [review]
Looks good.
