### PR TITLE
fix(Authoring): Check real mime type when author uploads a file

### LINKED ISSUE #186: Check real mime type when author uploads a file
When an author uploads a file that they aren't allowed to in the File Manager, they can spoof (manually change) the Content-Type to allow it to be uploaded.

1. Download the Burp Suite Community Edition (no need to enter email, just click "Go straight to downloads")
https://portswigger.net/burp/communitydownload

2. Install Burp Suite Community Edition

3. Launch Burp Suite Community Edition

4. Leave "Temporary project" selected
    - Click "Next"

5. Use Burp defaults
    - Click "Start Burp"

6. Configure the proxy
    - Click Proxy tab
    - Click Options tab
    - Under Proxy Listeners, highlight the 127.0.0.1:8080 line
    - Click "Edit"
    - Change port from 8080 to 8081

7. Launch the browser
    - Click Intercept tab
    - Click "Open browser"

8. Upload a file that should not be allowed
    - In the Burp browser go to localhost:81
    - Log in as a teacher
    - Open a unit in the Authoring Tool
    - Go to the File Manager view
    - Go back to the Burp application and click "Intercept is off" to turn intercept on
    - Go back to the Burp browser and drag and drop a php file into the File Manager
    - Go back to the Burp application and it should have intercepted the upload request
    - Change
        - Content-Type: application/octet-stream
        - to
        - Content-Type: image/jpeg
    - Click "Forward" button at the top left
    - The file will be uploaded when it shouldn't be

Right now we only look at the Content-Type which can be spoofed. We should try to detect the real mime type instead of relying on the Content-Type value.

### PR DESCRIPTION
**Pull request by geoffreykwan**
## Changes

Check a file's real MIME type when an author uploads a file to the File Manager.

## Test

1. Download the Burp Suite Community Edition (no need to enter email, just click "Go straight to downloads")
https://portswigger.net/burp/communitydownload

2. Install Burp Suite Community Edition

3. Launch Burp Suite Community Edition

4. Leave "Temporary project" selected
    - Click "Next"

5. Use Burp defaults
    - Click "Start Burp"

6. Configure the proxy
    - Click Proxy tab
    - Click Options tab
    - Under Proxy Listeners, highlight the 127.0.0.1:8080 line
    - Click "Edit"
    - Change port from 8080 to 8081

7. Launch the browser
    - Click Intercept tab
    - Click "Open browser"

8. Upload a file that should not be allowed
    - In the Burp browser go to localhost:81
    - Log in as a teacher
    - Open a unit in the Authoring Tool
    - Go to the File Manager view
    - Go back to the Burp application and click "Intercept is off" to turn intercept on
    - Go back to the Burp browser and drag and drop a php file into the File Manager
    - Go back to the Burp application and it should have intercepted the upload request
    - Change
        - Content-Type: application/octet-stream
        - to
        - Content-Type: image/jpeg
    - Click "Forward" button at the top left
    - The file should be rejected. Previously the file would be accepted.

Closes #186

### CODE REVIEW

File: src/main/java/org/wise/portal/presentation/web/controllers/author/project/ProjectAssetAPIController.java [hunk 1]
```diff
@@ -116,7 +121,20 @@ private boolean isUserAllowedToUpload(User user, MultipartFile file) {
       allowedTypes += ","
           + appProperties.getProperty("trustedAuthorAllowedProjectAssetContentTypes");
     }
-    return allowedTypes.contains(file.getContentType());
+    return allowedTypes.contains(getRealMimeType(file));
+  }
+
+  public String getRealMimeType(MultipartFile file) {
```
Comment (hirokiterashima) [inline src/main/java/org/wise/portal/presentation/web/controllers/author/project/ProjectAssetAPIController.java]:
```suggestion
  private String getRealMimeType(MultipartFile file) {
```

File: src/main/java/org/wise/portal/presentation/web/controllers/author/project/ProjectAssetAPIController.java [hunk 2]
```diff
@@ -116,7 +121,20 @@ private boolean isUserAllowedToUpload(User user, MultipartFile file) {
...
+    AutoDetectParser parser = new AutoDetectParser();
+    Detector detector = parser.getDetector();
+    try {
+      Metadata metadata = new Metadata();
+      TikaInputStream stream = TikaInputStream.get(file.getInputStream());
+      org.apache.tika.mime.MediaType mediaType = detector.detect(stream, metadata);
+      return mediaType.toString();
+    } catch (IOException e) {
+      return MimeTypes.OCTET_STREAM;
+    }
```
Comment (hirokiterashima) [inline src/main/java/org/wise/portal/presentation/web/controllers/author/project/ProjectAssetAPIController.java]: If we add OCTET_STREAM to allowedTypes in application.properties, could this allow someone to potentially upload a file that we do not support?

To handle this case, should this method throw the IOException instead of returning a default OCTET_STREAM, and catch the exception in isUserAllowedToUpload() method and return false there?

**Review by hirokiterashima — CHANGES_REQUESTED** [review]
Functionality works as described, but I had some questions about the code. See inline comments.

**Review by hirokiterashima — APPROVED** [review]

**Review by breity — APPROVED** [review]
