### PR TITLE
fix(Student Work): Only allow students to get their own work

### LINKED ISSUE #46: Only allow students to get their own student work
In StudentDataController.java the getWISE5StudentData() function should check whether the requester has access to view the work they are requesting.

### PR DESCRIPTION
**Pull request by geoffreykwan**
## Changes

Only allow students to get their own work.

## Test

- Make sure students can still get their own work
- Make sure students can still get classmate work in Discussion and Summary components (because they use a different endpoint)
- Make sure students can't get other workgroup's work, events, and annotations

You can log in as a student and try to retrieve data from other workgroups by changing the workgroupId in the url. Replace {runId} and {workgroupId}.

Url to get student work
```http://localhost:81/api/student/data?runId={runId}&workgroupId={workgroupId}&getStudentWork=true```

Url to get student events
```http://localhost:81/api/student/data?runId={runId}&workgroupId={workgroupId}&getEvents=true```

Url to get student annotations
```http://localhost:81/api/student/data?runId={runId}&getAnnotations=true&toWorkgroupId={workgroupId}```

Closes #46

### CODE REVIEW

File: src/main/java/org/wise/vle/web/wise5/StudentDataController.java [hunk 1]
```diff
@@ -157,6 +152,67 @@ public void getWISE5StudentData(HttpServletResponse response,
...
 
+  private boolean isAllowedToGetStudentData(User user, Run run, Integer workgroupId)
+      throws ObjectNotFoundException {
+    return isMemberOfWorkgroupId(user, run, workgroupId);
+  }
+
+  private boolean isAllowedToGetEvents(User user, Run run, Integer workgroupId)
+      throws ObjectNotFoundException {
+    return isMemberOfWorkgroupId(user, run, workgroupId);
+  }
```
Comment (breity) [inline src/main/java/org/wise/vle/web/wise5/StudentDataController.java]: Since these functions both just return the result of `isMemberOfWorkgroupId()`, do we need them or can you just call `isMemberOfWorkgroupId` in the places where they're invoked?

**Review by breity — APPROVED** [review]
Looks good.
